Template/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Template.Models;

namespace Template.Controllers
{
//MenuController - cambiando
    public class MenuController : Controller
    {
        [ChildActionOnly]
        public ActionResult Index()
        {
        //Lista de opciones
            List<MenuViewModel> menu = new List<MenuViewModel>
            {
                new MenuViewModel
                {
                    id = "1",
                    action = "Home/Index",
                    optionName = "Menu 1",
                    childOf = "",
                    icon = "dashboard",
                    order = 2,
                    selected = false
                },
                new MenuViewModel
                {
                    id = "2",
                    action = "",
                    optionName = "Menu 2",
                    childOf = "",
                    icon = "build",
                    order = 1,
                    selected = false
                },
                new MenuViewModel
                {
                    id = "3",
                    action = "",
                    optionName = "Menu 3",
                    childOf = "",
                    icon = "commute",
                    order = 3,
                    selected = false
                },
                new MenuViewModel
                {
                    id = "4",
                    action = "",
                    optionName = "Menu item 1",
                    childOf = "3",
                    icon = "face",
                    order = 2,
                    selected = false
                },
                new MenuViewModel
                {
                    id = "4",
                    action = "",
                    optionName = "Menu item 2",
                    childOf = "3",
                    icon = "face",
                    order = 1,
                    selected = false
                },
                new MenuViewModel
                {
                    id = "5",
                    action = "",
                    optionName = "Menu 4",
                    childOf = "",
                    icon = "flight_takeoff",
                    order = 5,
                    selected = false
                },
            };

            #region ITEM SELECTED

            string action = string.Format("{0}/{1}", 
                ControllerContext.ParentActionViewContext.RouteData.Values["controller"], 
                ControllerContext.ParentActionViewContext.RouteData.Values["action"]);

            menu.Where(a => a.action.ToUpper() == action.ToUpper()).Select(s => { s.selected = true; return s; }).ToList();

            #endregion

            return View("_SideBar", menu);
        }
    }
}

Template/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <link rel="apple-touch-icon" href="../assets/img/apple-icon.png">
    <link rel="icon" href="../assets/img/favicon.png">
    <title>
        Started template
    </title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="">
    <div class="wrapper">
        @{Html.RenderAction("Index", "Menu");}
        <div class="main-panel">
            <nav class="navbar navbar-expand-lg navbar-default navbar-transparent  navbar-absolute fixed-top">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-minimize">
                            <button id="minimizeSidebar" class="btn btn-just-icon btn-white btn-fab btn-round">
                                <i class="material-icons text_align-center visible-on-sidebar-regular">more_vert</i>
                                <i class="material-icons design_bullet-list-67 visible-on-sidebar-mini">view_list</i>
                                <div class="ripple-container"></div>
                            </button>
                        </div>
                        <a class="navbar-brand" href="#">Material Dashboard</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#">
                                    <i class="material-icons">dashboard</i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Stats</span>
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">notifications</i>
                                    <span class="notification">5</span>
                                    <p class="d-lg-none d-md-block">
                                        Some Actions
                                    </p>
                                    <div class="ripple-container"></div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#">Mike John responded to your email</a>
                                    <a class="dropdown-item" href="#">You have 5 new tasks</a>
                                    <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                                    <a class="dropdown-item" href="#">Another Notification</a>
                                    <a class="dropdown-item" href="#">Another One</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">person</i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Account</span>
                                    </p>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink2">
                                    <a class="dropdown-item" href="#">Mike John responded to your email</a>
                                    <a class="dropdown-item" href="#">You have 5 new tasks</a>
                                    <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                                    <a class="dropdown-item" href="#">Another Notification</a>
                                    <a class="dropdown-item" href="#">Another One</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            @RenderSection("footer", required: false)
        </div>
    </div>
@Html.Partial("_Loading")
</body>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</html>

Template/Views/Shared/_Loading.cshtml
<div id="spinner" class="modal fade" role="dialog" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="sk-circle">
                    <div class="sk-circle1 sk-child"></div>
                    <div class="sk-circle2 sk-child"></div>
                    <div class="sk-circle3 sk-child"></div>
                    <div class="sk-circle4 sk-child"></div>
                    <div class="sk-circle5 sk-child"></div>
                    <div class="sk-circle6 sk-child"></div>
                    <div class="sk-circle7 sk-child"></div>
                    <div class="sk-circle8 sk-child"></div>
                    <div class="sk-circle9 sk-child"></div>
                    <div class="sk-circle10 sk-child"></div>
                    <div class="sk-circle11 sk-child"></div>
                    <div class="sk-circle12 sk-child"></div>
                </div>
            </div>
        </div>
    </div>
</div>

Template/Views/Shared/_SideBar.cshtml
@model IEnumerable<Template.Models.MenuViewModel>
@{
    Layout = null;
}
<div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
    <div class="logo">
        <a href="#" class="simple-text logo-normal">
            DEMO
        </a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            @TreeViewMenu.GetTreeView(Model.OrderBy(o => o.order).ToList(), Model.FirstOrDefault().childOf)
        </ul>
    </div>
</div>